package com.payrail.common.error;

public enum ErrorCode {
    VALIDATION_ERROR,
    INVALID_CREDENTIALS,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    EMAIL_ALREADY_EXISTS,
    WEAK_PASSWORD,
    INVALID_STATE_TRANSITION,
    INTERNAL_ERROR,
    IDEMPOTENCY_KEY_CONFLICT,
}